language: node_js
node_js:
  - 6.3.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: ab301ba1fd0c821438fa5ee4011ea974a0f894c47781a056ccefb61d878de18e
env:
  global:
    - CXX=g++-4.8
services:
  - redis-server
before_install: 
  - npm install -g npm
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
after_script:
  - istanbul cover node_modules/.bin/_mocha -- -R dot
  - codeclimate-test-reporter < coverage/lcov.info
  - grunt coveralls
